# --------------------------- #
# SETTINGS SECTION
# --------------------------- #
SETTINGS:
    # number of concurrent threads
    THREADS: 1

    # number of retries for ANY action
    ATTEMPTS: 5
    
    # account range.
    # BY DEFAULT: [0, 0] - all accounts
    # [3, 5] - only 3 4 5 accounts
    # [7, 7] - only 7 account
    ACCOUNTS_RANGE: [0, 0]
    
    # WORKS ONLY IF ACCOUNTS_RANGE IS [0, 0]
    # exact accounts to use.
    # BY DEFAULT: [] - all accounts
    # Example: [1, 4, 6] - bot will use only 1, 4 and 6 accounts
    EXACT_ACCOUNTS_TO_USE: []
    
    SHUFFLE_WALLETS: true

    # pause between attempts
    PAUSE_BETWEEN_ATTEMPTS: [5, 10]
    
    # pause between swaps
    PAUSE_BETWEEN_SWAPS: [10, 20]
    
    # pause in seconds between accounts
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [10, 20]
    
    # pause in seconds between actions
    RANDOM_PAUSE_BETWEEN_ACTIONS: [10, 20]
    
    # random pause before start of every account
    # to make sure that all accounts will be started at different times
    RANDOM_INITIALIZATION_PAUSE: [10, 50]
    
    # if true, bot will send logs to telegram
    SEND_TELEGRAM_LOGS: false
    # telegram bot token
    TELEGRAM_BOT_TOKEN: "12317283:lskjalsdfasdfasd-sdfadfasd"
    # telegram users ids
    TELEGRAM_USERS_IDS: [235123432]


FLOW:
    # if task from database failed, bot will skip it
    # if false, bot will stop and show error
    SKIP_FAILED_TASKS: false


CAPTCHA:
    SOLVIUM_API_KEY: "xxxxxxxxxxxxxxxx"


LOYALTY:
    REPLACE_FAILED_TWITTER_ACCOUNT: true
    MAX_ATTEMPTS_TO_COMPLETE_QUEST: 15

RPCS:
    CAMP_NETWORK: ["https://rpc.basecamp.t.raas.gelato.cloud"]


OTHERS:
    SKIP_SSL_VERIFICATION: true
    USE_PROXY_FOR_RPC: true
  
CRUSTY_SWAP:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Optimism", "Base"]
    AMOUNT_TO_REFUEL: [0.0002, 0.0003]
    MINIMUM_BALANCE_TO_REFUEL: 99999
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999
    BRIDGE_ALL: false
    BRIDGE_ALL_MAX_AMOUNT: 0.01

# --------------------------- #
# EXCHANGES SECTION
# --------------------------- #
EXCHANGES:
    name: "OKX"  # Supported: "OKX", "BITGET"
    apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    secretKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    passphrase: 'xxxxxxx'  
    withdrawals:
        - currency: "ETH" # ONLY ETH
          networks: ["Arbitrum", "Optimism"] # ["Arbitrum", "Base", "Optimism"]
          min_amount: 0.0004
          max_amount: 0.0006
          max_balance: 0.005
          wait_for_funds: true
          max_wait_time: 99999  # in seconds
          retries: 3